import React from "react";

const DashboardIcon = <i className="bx bx-home side-menu__icon"></i>;

const PagesIcon = <i className="bx bx-file-blank side-menu__icon"></i>;

const TaskIcon = <i className="bx bx-task side-menu__icon"></i>;

const AuthenticationIcon = (
  <i className="bx bx-fingerprint side-menu__icon"></i>
);

const ErrorIcon = <i className="bx bx-error side-menu__icon"></i>;

const UiElementsIcon = <i className="bx bx-box side-menu__icon"></i>;

const Utilities = <i className="bx bx-medal side-menu__icon"></i>;

const FormsIcon = <i className="bx bx-file  side-menu__icon"></i>;

const AdvancedUiIcon = <i className="bx bx-party side-menu__icon"></i>;

const WidgetsIcon = <i className="bx bx-gift side-menu__icon"></i>;

const AppsIcon = <i className="bx bx-grid-alt side-menu__icon"></i>;

const NestedmenuIcon = <i className="bx bx-layer side-menu__icon"></i>;

const TablesIcon = <i className="bx bx-table side-menu__icon"></i>;

const ChartsIcon = <i className="bx bx-bar-chart-square side-menu__icon"></i>;

const MapsIcon = <i className="bx bx-map side-menu__icon"></i>;

const Icons = <i className="bx bx-store-alt side-menu__icon"></i>;

const badge = (
  <span className="badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-1">
    12
  </span>
);
const badge1 = (
  <span className="text-secondary text-[0.75em] rounded-sm !py-[0.25rem] !px-[0.45rem] badge !bg-secondary/10 ms-1">
    New
  </span>
);
const badge2 = (
  <span className="text-danger text-[0.75em] rounded-sm badge !py-[0.25rem] !px-[0.45rem] !bg-danger/10 ms-1">
    Hot
  </span>
);
const badge4 = (
  <span className="text-success text-[0.75em] badge !py-[0.25rem] !px-[0.45rem] rounded-sm bg-success/10 ms-1">
    3
  </span>
);

export const MenuItems: any = [
  {
    menutitle: "MAIN",
  },

  {
    icon: DashboardIcon,
    badgetxt: badge,
    title: "Dashboards",
    type: "sub",
    active: false,
    selected: false,
    children: [
      {
        path: "/dashboards/crm",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "CRM",
      },
      {
        path: "/dashboards/ecommerce",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Ecommerce",
      },
      {
        path: "/dashboards/crypto",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Crypto",
      },
      {
        path: "/dashboards/jobs",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Jobs",
      },
      {
        path: "/dashboards/nft",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "NFT",
      },
      {
        path: "/dashboards/sales",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Sales",
      },
      {
        path: "/dashboards/analytics",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Analytics",
      },
      {
        path: "/dashboards/projects",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Projects",
      },
      {
        path: "/dashboards/hrm",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "HRM",
      },
      {
        path: "/dashboards/stocks",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Stocks",
      },
      {
        path: "/dashboards/courses",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Courses",
      },
      {
        path: "/dashboards/personal",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Personal",
      },
    ],
  },

  {
    menutitle: "PAGES",
  },

  {
    icon: PagesIcon,
    badgetxt: badge1,
    title: "Pages",
    type: "sub",
    active: false,
    selected: false,
    children: [
      {
        path: "/pages/about-us",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "About Us",
      },
      {
        title: "Blog",
        type: "sub",
        active: false,
        children: [
          {
            path: "/pages/blog/blog",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Blog",
          },
          {
            path: "/pages/blog/blog-details",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Blog-Details",
          },
          {
            path: "/pages/blog/create-blog",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Create-Blog",
          },
        ],
      },
      {
        path: "/pages/chat",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Chat",
      },
      {
        path: "/pages/contacts",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Contacts",
      },
      {
        path: "/pages/contact-us",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Contact-Us",
      },
      {
        title: "Ecommerce",
        type: "sub",
        active: false,
        children: [
          {
            path: "/pages/ecommerce/add-products",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Add Products",
          },
          {
            path: "/pages/ecommerce/cart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Cart",
          },
          {
            path: "/pages/ecommerce/checkout",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Checkout",
          },
          {
            path: "/pages/ecommerce/edit-products",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Edit Products",
          },
          {
            path: "/pages/ecommerce/order-details",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Order Details",
          },
          {
            path: "/pages/ecommerce/orders",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Orders",
          },
          {
            path: "/pages/ecommerce/products",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Products",
          },
          {
            path: "/pages/ecommerce/product-details",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Product Details",
          },
          {
            path: "/pages/ecommerce/product-list",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Products List",
          },
          {
            path: "/pages/ecommerce/wishlist",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Wishlist",
          },
        ],
      },
      {
        title: "Email",
        type: "sub",
        active: false,
        children: [
          {
            path: "/pages/email/mail-app",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Mail-App",
          },
          {
            path: "/pages/email/mail-settings",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Mail-Settings",
          },
        ],
      },
      {
        path: "/pages/empty",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Empty",
      },
      {
        path: "/pages/faqs",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "FAQ's",
      },
      {
        title: "File Manager",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/pages/filemanager",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "File Manager",
          },
        ],
      },
      {
        title: "Invoice",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/pages/invoice/create-invoice",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Create Invoice",
          },
          {
            path: "/pages/invoice/invoice-details",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Invoice Details",
          },
          {
            path: "/pages/invoice/invoice-list",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Invoice List",
          },
        ],
      },
      {
        path: "/landing",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Landing",
      },
      {
        path: "/jobs-landing",
        badgetxt: badge1,
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Jobs Landing",
      },
      {
        path: "/pages/notifications",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Notifications",
      },
      {
        path: "/pages/pricing",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Pricing",
      },
      {
        path: "/pages/profile",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Profile",
      },
      {
        path: "/pages/reviews",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Reviews",
      },
      {
        path: "/pages/team",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Team",
      },
      {
        path: "/pages/terms&conditions",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Terms & Conditions",
      },
      {
        path: "/pages/timeline",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Timeline",
      },
      {
        path: "/pages/todo-list",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "To Do List",
      },
    ],
  },
  {
    icon: TaskIcon,
    title: "Task",
    badgetxt: badge1,
    type: "sub",
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/task/kanban-board",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Kanban Board",
      },
      {
        path: "/task/list-view",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "List View",
      },
      {
        path: "/task/task-details",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Task Details",
      },
    ],
  },
  {
    icon: AuthenticationIcon,
    title: " Authentication",
    type: "sub",
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/authentication/coming-soon",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Coming Soon",
      },

      {
        title: "Create Password",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/authentication/create-password/create-basic",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Basic",
          },
          {
            path: "/authentication/create-password/create-cover",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Cover",
          },
        ],
      },
      {
        title: "Lock Screen",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/authentication/lock-screen/screen-basic",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Basic",
          },
          {
            path: "/authentication/lock-screen/screen-cover",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Cover",
          },
        ],
      },
      {
        title: "Reset Password",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/authentication/reset-password/reset-basic",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Basic",
          },
          {
            path: "/authentication/reset-password/reset-cover",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Cover",
          },
        ],
      },
      {
        title: "Sign Up",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/authentication/sign-up/signup-basic",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Basic",
          },
          {
            path: "/authentication/sign-up/signup-cover",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Cover",
          },
        ],
      },
      {
        title: "Sign In",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/authentication/sign-in/signin-basic",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Basic",
          },
          {
            path: "/authentication/sign-in/signin-cover",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Cover",
          },
        ],
      },
      {
        title: "Two Step Verification",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/authentication/two-step-verification/two-basic",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Basic",
          },
          {
            path: "/authentication/two-step-verification/two-cover",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Cover",
          },
        ],
      },
      {
        path: "/authentication/under-maintanance",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Under Maintainance",
      },
    ],
  },
  {
    icon: ErrorIcon,
    title: "Error",
    type: "sub",
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/error/error-401",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "401-Error",
      },
      {
        path: "/error/error-404",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "404-Error",
      },
      {
        path: "/error/error-500",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "500-Error",
      },
    ],
  },

  {
    menutitle: "GENERAL",
  },
  {
    title: "Ui Elements",
    icon: UiElementsIcon,
    type: "sub",
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/ui-elements/alerts",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Alerts",
      },
      {
        path: "/ui-elements/badge",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Badge",
      },
      {
        path: "/ui-elements/breadcrumb",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Breadcrumb",
      },
      {
        path: "/ui-elements/buttons",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Buttons",
      },
      {
        path: "/ui-elements/button-group",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Button Group",
      },
      {
        path: "/ui-elements/blockquotes",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Blockquotes",
      },
      {
        path: "/ui-elements/cards",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Cards",
      },
      {
        path: "/ui-elements/dropdowns",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Dropdowns",
      },
      {
        path: "/ui-elements/images&figures",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Images & Figures",
      },
      {
        path: "/ui-elements/list-group",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "List Group",
      },
      {
        path: "/ui-elements/navs&tabs",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Navs & Tabs",
      },
      {
        path: "/ui-elements/object-fit",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Object Fit",
      },
      {
        path: "/ui-elements/pagination",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Pagination",
      },
      {
        path: "/ui-elements/popovers",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Popovers",
      },
      {
        path: "/ui-elements/progress",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Progress",
      },
      {
        path: "/ui-elements/indicator",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Indicators",
      },
      {
        path: "/ui-elements/spinners",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Spinners",
      },
      {
        path: "/ui-elements/toasts",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Toasts",
      },
      {
        path: "/ui-elements/tooltips",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Tooltips",
      },
    ],
  },
  {
    title: "Utilities",
    icon: Utilities,
    type: "sub",
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/utilities/avatars",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Avatars",
      },
      {
        path: "/utilities/borders",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Borders",
      },
      {
        path: "/utilities/colors",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Colors",
      },
      {
        path: "/utilities/grids",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Grids",
      },
      {
        path: "/utilities/flex",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Flex",
      },
      {
        path: "/utilities/columns",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Columns",
      },
      {
        path: "/utilities/typography",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Typography",
      },
    ],
  },
  {
    title: "Forms",
    icon: FormsIcon,
    type: "sub",
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        title: "Form Elements",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/forms/formelements/inputs",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Inputs",
          },
          {
            path: "/forms/formelements/checks&radios",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "checks & Radios ",
          },
          {
            path: "/forms/formelements/formswitch",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Form switch",
          },
          {
            path: "/forms/formelements/input-group",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Input Group",
          },
          {
            path: "/forms/formelements/form-select",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Form select",
          },
          {
            path: "/forms/formelements/range-slider",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Range Slider",
          },
          {
            path: "/forms/formelements/file-uploads",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "File Uploads",
          },
          {
            path: "/forms/formelements/date-time-picker",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Date,Time Picker",
          },
          {
            path: "/forms/formelements/color-picker",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Color Pickers",
          },
          {
            path: "/forms/formelements/advancedselect",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Advanced Select",
          },
          {
            path: "/forms/formelements/inputnumber",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Input Number",
          },
          {
            path: "/forms/formelements/passwords",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Passwords",
          },
          {
            path: "/forms/formelements/countermarkup",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Counters & Markup",
          },
        ],
      },
      {
        path: "/forms/form-layouts",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Form Layouts",
      },
      {
        title: "Form Editors",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/forms/formeditors",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Quill Editors",
          },
        ],
      },
      {
        path: "/forms/validation",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Validation",
      },
      {
        path: "/forms/select2",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Select2",
      },
    ],
  },
  {
    title: "Advanced Ui",
    icon: AdvancedUiIcon,
    type: "sub",
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/advanced-ui/accordions&collapse",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Accordions & collapse",
      },
      {
        path: "/advanced-ui/customscrollbar",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Custom scrollbar",
      },
      {
        path: "/advanced-ui/draggable-cards",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Draggable Cards",
      },
      {
        path: "/advanced-ui/modals&closes",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Modals & Closes",
      },
      {
        path: "/advanced-ui/navbar",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Navbar",
      },
      {
        path: "/advanced-ui/offcanvas",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Offcanvas",
      },
      {
        path: "/advanced-ui/ratings",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Ratings",
      },
      {
        path: "/advanced-ui/swiper-js",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Swiper JS",
      },
      {
        path: "/advanced-ui/stepper",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Stepper",
      },
    ],
  },
  {
    path: "/widgets",
    title: "widgets",
    icon: WidgetsIcon,
    badgetxt: badge2,
    type: "link",
    active: false,
    selected: false,
    dirchange: false, 
  },

  {
    menutitle: "WEB APPS",
  },
  {
    title: "Apps",
    icon: AppsIcon,
    type: "sub",
    badgetxt: badge1,
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/apps/full-calendar",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Full Calendar",
      },
      {
        path: "/apps/gallery",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Gallery",
      },
      {
        title: "Projects",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/apps/projects/project-list",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Project List",
          },
          {
            path: "/apps/projects/project-overview",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Project Overview",
          },
          {
            path: "/apps/projects/create-project",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Create Project",
          },
        ],
      },
      {
        title: "Jobs",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/apps/jobs/job-details",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Job Details",
          },
          {
            path: "/apps/jobs/search-company",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Search Company",
          },
          {
            path: "/apps/jobs/search-jobs",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Search Jobs",
          },
          {
            path: "/apps/jobs/job-post",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: " Job Post",
          },
          {
            path: "/apps/jobs/jobs-list",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: " Jobs List",
          },
          {
            path: "/apps/jobs/search-candidate",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: " Search Candidate",
          },
          {
            path: "/apps/jobs/candidate-details",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Candidate details",
          },
        ],
      },
      {
        title: "NFT",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/apps/nft/market-place",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Market Place",
          },
          {
            path: "/apps/nft/nft-details",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "NFT Details",
          },
          {
            path: "/apps/nft/create-nft",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Create NFT",
          },
          {
            path: "/apps/nft/wallet-integration",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: " Wallet Integration",
          },
          {
            path: "/apps/nft/live-auction",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Live Auction",
          },
        ],
      },
      {
        title: "CRM",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/apps/crm/contacts",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Contacts",
          },
          {
            path: "/apps/crm/companies",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Companies",
          },
          {
            path: "/apps/crm/deals",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Deals",
          },
          {
            path: "/apps/crm/leads",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: " Leads",
          },
        ],
      },
      {
        title: "Crypto",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/apps/crypto/transactions",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Transactions",
          },
          {
            path: "/apps/crypto/currency-exchange",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Currency Exchanges",
          },
          {
            path: "/apps/crypto/buy&sell",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Buy & Sell",
          },
          {
            path: "/apps/crypto/market-cap",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: " Marketcap",
          },
          {
            path: "/apps/crypto/wallet",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Wallet",
          },
        ],
      },
    ],
  },
  {
    icon: NestedmenuIcon,
    title: "Nested Menu",
    selected: false,
    active: false,
    type: "sub",
    children: [
      {
        path: "",
        title: "Nested-1",
        type: "empty",
        active: false,
        selected: false,
        dirchange: false, 
      },

      {
        title: "Nested-2",
        type: "sub",
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "",
            type: "empty",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Nested-2-1",
          },
          {
            path: "",
            type: "empty",
            ctive: false,
            selected: false,
            dirchange: false, 
            title: "Nested-2-2",
          },
          {
            path: "",
            type: "empty",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Nested-2-3",
          },
        ],
      },
    ],
  },

  {
    menutitle: "TABLES & CHARTS",
  },
  {
    title: "Tables",
    icon: TablesIcon,
    type: "sub",
    menutitle: "",
    badgetxt: badge4,
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/tables/table",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Tables",
      },
      {
        path: "/tables/gridjs-table",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Grid JS Tables",
      },
      {
        path: "/tables/data-table",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Data Tables",
      },
    ],
  },

  {
    title: "Charts",
    icon: ChartsIcon,
    type: "sub",
    selected: false,
    active: false,
    children: [
      {
        title: "Apex Charts",
        type: "sub",
        menusub: true,
        active: false,
        selected: false,
        dirchange: false, 
        children: [
          {
            path: "/charts/apexcharts/line-charts",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Line Charts",
          },
          {
            path: "/charts/apexcharts/area-charts",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Area Charts ",
          },
          {
            path: "/charts/apexcharts/column-charts",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Column Charts",
          },
          {
            path: "/charts/apexcharts/bar-charts",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Bar Charts",
          },
          {
            path: "/charts/apexcharts/mixed-charts",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Mixed Charts",
          },
          {
            path: "/charts/apexcharts/range-area-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Range Area Charts",
          },
          {
            path: "/charts/apexcharts/timeline-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Timeline Charts",
          },
          {
            path: "/charts/apexcharts/candlestick-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "CandleStick Charts",
          },
          {
            path: "/charts/apexcharts/boxplot-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Boxplot Charts",
          },
          {
            path: "/charts/apexcharts/bubble-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Bubble Charts",
          },
          {
            path: "/charts/apexcharts/scatter-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Scatter Charts",
          },
          {
            path: "/charts/apexcharts/heatmap-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Heatmap Charts",
          },
          {
            path: "/charts/apexcharts/treemap-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Treemap Charts",
          },
          {
            path: "/charts/apexcharts/pie-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Pie Charts",
          },
          {
            path: "/charts/apexcharts/radialbar-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Radialbar Charts",
          },
          {
            path: "/charts/apexcharts/radar-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Radar Charts",
          },
          {
            path: "/charts/apexcharts/polararea-chart",
            type: "link",
            active: false,
            selected: false,
            dirchange: false, 
            title: "Polararea Charts",
          },
        ],
      },
      {
        path: "/charts/chartjs",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "ChartJS Charts",
      },
      {
        path: "/charts/echart",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Echart Charts",
      },
    ],
  },

  { menutitle: "MAPS & ICONS" },
  {
    title: "Maps",
    icon: MapsIcon,
    type: "sub",
    background: "hor-rightangle",
    active: false,
    selected: false,
    dirchange: false, 
    children: [
      {
        path: "/maps/leaflet-map",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Leaflet Maps",
      },
      {
        path: "/maps/vector-maps",
        type: "link",
        active: false,
        selected: false,
        dirchange: false, 
        title: "Vector Maps",
      },
    ],
  },
  {
    path: "/icons",
    icon: Icons,
    type: "link",
    active: false,
    selected: false,
    dirchange: false, 
    title: "Icons",
  },
];
